# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: rally
  type: group
  version: 2.0.0
  role: [rally]
  tasks:
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
    - puppet-demo
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: one_by_one


- id: puppet-demo
  type: puppet
  version: 2.0.0
  role: [rally]
  requires: [netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/demo.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
  reexecute_on:
    - deploy_changes