# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: rally
  type: group
  version: 2.0.0
  role: [rally]
  tasks:
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
    - rally-hiera-override
    - rally-deploy
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: one_by_one


# Tasks definitions for the deployment
######################################

# This task needs to be reexecuted to adapt the configuration parameters which
# depend on the number of nodes in the cluster
- id: rally-hiera-override
  type: puppet
  version: 2.0.0
  requires: [netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/hiera_override.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120

- id: rally-deploy
  type: puppet
  version: 2.0.0
  role: [rally]
  requires: [netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/deploy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600