attributes:
  metadata:
    label: "Rally benchmarking tool"
    weight: 90

  rally_configuration:
    value: 'Some config'
    label: 'Repository for example'
    description: 'Configurable parameter'
    weight: 5
    type: "text"